### ISSUE TITLE
1.12.4 server fails to start

### ISSUE THREAD

**Issue by XygenSS** [Iskallia/Vault-public#751]
Upgraded server to newest version, server fails to start even with a fresh install. 
Server runs on debian hosted on google compute engine, c2-standard-4. Assigned 10GB ram

Some bits of the log that catch my eye:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/minecraft/libraries/cpw/mod
s/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Any help would be appreciated.

<details>
<summary>click to enlarge full log</summary>
<br>
root@vaulthunters-server:/home/minecraft# java -Xms1G -Xmx10G -jar forge-1.16.5-36.2.23.jar nogui
[10:35:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fm
lserver, --fml.forgeVersion, 36.2.23, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup,
 net.minecraftforge, nogui]
[10:35:24] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 
11.0.14 by Debian
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/minecraft/libraries/cpw/mod
s/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[10:35:24] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[10:35:24] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/minecraft/libraries/
org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:25] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engi
ne is planned to be removed from a future JDK release
[10:35:26] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recogn
ition error at: '~'
Exception in thread "main" [10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.l
ang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Sec
ureJarHandler.createCodeSource(SecureJarHandler.java:66)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Tra
nsformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)

[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Tra
nsformingClassLoader.loadClass(TransformingClassLoader.java:136)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Tra
nsformingClassLoader.loadClass(TransformingClassLoader.java:98)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.Clas
sLoader.loadClass(ClassLoader.java:522)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.Clas
s.forName0(Native Method)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.Clas
s.forName(Class.java:398)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.se
rvice.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.la
unch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[10:35:29] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.la
[11:43:08] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'                              
Exception in thread "main" [11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NoSuchMethodError: 'void sun.security.util.Ma
nifestEntryVerifier.<init>(java.util.jar.Manifest)'                                                                                                                 
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.j
ava:66)                                                                                                                                                             
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findCla
ss(TransformingClassLoader.java:275)                                                                                                                                
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassL
oader.java:136)                                                                                                                                                     
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassL
oader.java:98)                                                                                                                                                      
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)          
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.Class.forName0(Native Method)                        
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.lang.Class.forName(Class.java:398)                        
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findCl
ass(ModLauncherClassProvider.java:67)                                                                                                                               
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnector
s(MixinConnectorManager.java:70)                                                                                                                                    
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinC
onnectorManager.java:59)                                                                                                                                            
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPl
atformManager.java:196)                                                                                                                                             
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:20
2)                                                                                                                                                                  
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(Mix
inLaunchPluginLegacy.java:201)                                                                                                                                      
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(Mix
inLaunchPluginLegacy.java:195)                                                                                                                                      
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPl
uginHandler.java:97)                                                                                                                                                
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at java.base/java.util.HashMap.forEach(HashMap.java:1337)                   
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandl
er.java:97)                                                                                                                                                         
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.jav
a:52)                                                                                                                                                               
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.jav
a:72)                                                                                                                                                               
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)                      
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)                     
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:6
3)                                                                                                                                                               
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60
)                                                                                                                                                                   
[11:43:11] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:       at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)            
root@vaulthunters-server:/home/minecraft# 
</details>

**Comment by 0ut4t1m3** [comment]
Try downgrading your Java 8 install to Update 311 if you're currently running Update 321. That should fix the issue for the time being.

**Comment by jadc** [comment]
This is still an issue, btw. Please update the pack's forge version a little bit, it is fixed in version 36.2.26+.
https://github.com/McModLauncher/modlauncher/issues/91
